### PR TITLE
Fix issue with HttpChannel linked list.

### LINKED ISSUE #504: Linked List of HttpChannels is broken
https://github.com/actix/actix-web/blob/cdb57b840e138a60b6b733648008ca877a916e2b/src/server/channel.rs#L80

should be: `if self.node.is_none() {`

Otherwise the `HttpChannel` object are never added to the `Node` linked list.

Also the `traverse` method should either be renamed `shutdown` or take a closure to call on each element.

I found these issues when trying to dump the status of all active connections (to debug the leaking connections issue).

### PR DESCRIPTION
**Pull request by Neopallium**
Closes #504.

### CODE REVIEW

**Comment by fafhrd91** [comment]
Could you rebase Pr against master

**Comment by Neopallium** [comment]
rebased

**Comment by Neopallium** [comment]
I just realized that the "update branch" button on github does a merge not a rebase.  Should I do a real rebase with git before sending PR requests?

Normally I don't rebase a branch if it would require a "force update" to push.  But it does make for nicer merges.

**Comment by DoumanAsh** [comment]
Hmmm strangely enough when I try to view all changes it show too few fils and changes...
Could you maybe try to rebase your branch?

**Comment by Neopallium** [comment]
trying to rebase right now.

**Comment by Neopallium** [comment]
Ok.  Finally got a clean rebase.  Now the PR only has 2 commits and 2 files changed.

File: src/server/http.rs [hunk 1]
```diff
@@ -637,7 +637,7 @@ where
 
     fn shutdown(&self, force: bool) {
         if force {
-            self.settings.head().traverse::<TcpStream, H>();
+            self.settings.head().traverse(|ch: &mut HttpChannel<TcpStream, H>| ch.shutdown());
```
Comment (DoumanAsh) [inline src/server/http.rs:640]: Is argument type here necessary?

File: src/server/channel.rs [hunk 2]
```diff
@@ -77,7 +77,7 @@ where
     type Error = ();
 
     fn poll(&mut self) -> Poll<Self::Item, Self::Error> {
-        if self.node.is_some() {
+        if self.node.is_none() {
```
Comment (DoumanAsh) [inline src/server/channel.rs:80]: Hm really strange how exactly it supposed to work in past 😄

Comment (Neopallium) [reply src/server/channel.rs:80]: The linked list seems to only be used for graceful shutdown.

File: src/server/http.rs (hunk 1 above)
Comment (Neopallium) [reply src/server/http.rs:640]: I only added the type because it wouldn't compile without it.  I am new to rust, so maybe I am missing something in the definition of the traverse method?

Comment (DoumanAsh) [reply src/server/http.rs:640]: Ah sorry then, I was expecting that Rust would be able to see the type here(since it should see it from `self.settings.head()`), but if not. My  bad, I mistook it.

**Review by DoumanAsh — APPROVED** [review]

**Comment by DoumanAsh** [comment]
@Neopallium Could  you please prepare entry in changelog?

**Comment by Neopallium** [comment]
@DoumanAsh Done.  Is the format of the entry correct?

**Comment by Neopallium** [comment]
Also rebased.

**Comment by DoumanAsh** [comment]
@Neopallium Yes, Thank you

**Comment by DoumanAsh** [comment]
@Neopallium I think you have rights to merge, so once CI is passed, feel free to 😄
