### PR TITLE
fix(actix-web): improve streaming response behavior for Content-Length and Content-Type

### LINKED ISSUE #2306: [awc] HTTP client ignores Content-Length if Body is stream.
## Expected Behavior

HTTP client should respect Content-Length even body of request is stream.

## Current Behavior

Content-Length header is removed by client itself.

## Possible Solution

respect Content-Length header if present.
also an enhancement, if first item of body stream is known as `None` it is better set Content-Length to zero. not inserting chunked encoding header.

## Steps to Reproduce (for bugs)

Send request with empty stream. 

## Context

Cloudfront will reject you.

## Your Environment

* Rust Version (I.e, output of `rustc -V`): rustc 1.53.0 (53cb7b09b 2021-06-17)
* Actix Web Version: awc 3.0.0-beta.7

### PR DESCRIPTION
**Pull request by JohnTitor**
## PR Type

Bug Fix

## PR Checklist

- [x] Tests for the changes have been added / updated.
- [x] Documentation comments have been added / updated.
- [x] A changelog entry has been made for the appropriate packages.
- [x] Format code with the latest stable rustfmt.
- [x] (Team) Label with affected crates and semver status.

## Overview

This is a rebase of https://github.com/actix/actix-web/pull/3015/ as I cannot push additional commits.

- Set default Content-Type to application/octet-stream for streaming responses
- Respect Content-Length header by automatically calling `no_chunking()` when set
- Resolves issue where Content-Length was ignored in streaming responses

Fixes #2306, closes #3015

### CODE REVIEW

File: actix-web/src/response/builder.rs [hunk 1]
```diff
@@ -318,12 +318,33 @@ impl HttpResponseBuilder {
...
+
+        if let Some(parts) = self.inner() {
+            if let Some(length) = parts.headers.get(header::CONTENT_LENGTH) {
+                if let Ok(length) = length.to_str() {
+                    if let Ok(length) = length.parse::<u64>() {
+                        self.no_chunking(length);
+                    }
+                }
+            }
+        }
```
Comment (robjtede) [inline actix-web/src/response/builder.rs:346]: this won't do anything due to https://github.com/actix/actix-web/blob/8996198f2c922e7c052a85d69022515440cac66d/actix-http/src/h1/encoder.rs#L147

we should encourage using SizedStream if the size is known, also plays better with body-altering middleware like compression

Comment (JohnTitor) [reply actix-web/src/response/builder.rs:346]: Sorry for the late reply! (Actually I didn't notice you comment, sorry.)

I might be wrong but `skip_len` would be false when no_chunking?
https://github.com/actix/actix-web/blob/8996198f2c922e7c052a85d69022515440cac66d/actix-http/src/h1/encoder.rs#L94-L104

But in general I agree with using SizedStream, I'll submit a follow-up patch!
