### PR TITLE
Relax MessageBody limit to 2048kb

### LINKED ISSUE #2101: awc: "Payload reached size limit" error on 6% of websites
## Expected Behavior
awc being able to successfully download the websites that work with curl and Firefox.

## Current Behavior
On some websites, e.g. http://thenaic.org, awc fails with the following error:

> Payload reached size limit.

61771 websites out of the top million are affected. List of all affected websites: [payload-size-reached-domain-list.txt.gz](https://github.com/actix/actix-web/files/6179134/payload-size-reached-domain-list.txt.gz)

## Steps to Reproduce (for bugs)
1. `git clone https://github.com/Shnatsel/rust-http-clients-smoke-test`
2. `cd rust-http-clients-smoke-test/awc`
3. `cargo build --release`
4. `target/release/awc-smoke-test thenaic.org`

## Context
I am testing a bunch of HTTP clients on the top million websites according to the [Feb 3 Tranco list](https://tranco-list.eu/list/3G6L).

## Your Environment
Linux, Ubuntu 20.04 LTS

* Rust Version (I.e, output of `rustc -V`): rustc 1.47.0 (18bf6b4f0 2020-10-07)
* Actix Web Version: awc 3.0.0-beta.3

### PR DESCRIPTION
**Pull request by fakeshadow**
## PR Type

Refactor

## PR Checklist

- [x] Tests for the changes have been added / updated.
- [x] Documentation comments have been added / updated.
- [x] Format code with the latest stable rustfmt.
- [x] (Team) Label with affected crates and semver status.

## Overview

Relax default limit to `MessageBody` type. 
No upfront reserve allocation for `ReadBody`'s buf.

Closes #2101

### CODE REVIEW

File: awc/src/response.rs [hunk 1]
```diff
@@ -228,12 +228,14 @@ impl<S> fmt::Debug for ClientResponse<S> {
     }
 }
 
+// Default ReadBody limit.
+const BODY_LIMIT: usize = 1024 * 2 * 1024;
```
Comment (robjtede) [inline awc/src/response.rs]:
```suggestion
const DEFAULT_BODY_LIMIT: usize = 1024 * 2 * 1024;
```

**Review by robjtede — APPROVED** [review]
LGTM 👍🏻

**Comment by robjtede** [comment]
merge at your leisure when checks done
