### PR TITLE
Fix cyclic references in ResourceMap

### LINKED ISSUE #1582: ResourceMap debug printing is infinitely recursive for any meaningful routing structure
## Expected Behavior

Debug printing a resource map with nested resource maps should not stack overflow.

## Current Behavior

Debug printing a resource map with nested resource maps recurses infinitely and overflows the stack.

## Possible Solution

Provide an explicit Debug impl that accounts for the cyclic structure.

## Steps to Reproduce
```rust
println!("{:?}", req.resource_map());

> thread 'xxx' has overflowed its stack
```

## Context

Trying to determine the finalized structure of a resource map while testing a new feature.

## Your Environment

* Rust Version (I.e, output of `rustc -V`): 1.40.0
* Actix Web Version: master (3.0.0-alpha.3)

### PR DESCRIPTION
**Pull request by mattgathu**
## PR Type

Bug Fix

## PR Checklist
Check your PR fulfills the following:

- [x] Tests for the changes have been added / updated.
- [x] A changelog entry has been made for the appropriate packages.
- [x] Format code with the latest stable rustfmt

## Overview

What
--
Refactor `ResourceMap` struct to remove hard references to parent ResourceMap.

How
--
Assuming the child resource maps are always nested within a parent, then
we can always assume the parent will be there and use a weak reference to
refer back to it.

> A Weak pointer is useful for keeping a temporary reference to the allocation managed by Rc without preventing its inner value from being dropped. It is also used to prevent circular references between Rc pointers, since mutual owning references would never allow either Rc to be dropped. For example, a tree could have strong Rc pointers from parent nodes to children, and Weak pointers from children back to their parents.

[_from the stdlib docs_](https://doc.rust-lang.org/nightly/std/rc/struct.Weak.html)

Closes https://github.com/actix/actix-web/issues/1582

### CODE REVIEW

**Comment by mattgathu** [comment]
@robjtede I started working on a fix for #1582 .

It's still a draft PR but the bug is essentially fixed now. I managed to have the following program compile and have debug working.

```rust
use actix_web::{get, App, web,HttpResponse, HttpRequest,  HttpServer};

#[get("/rmap")]
async fn rmap(req:HttpRequest) -> String {
    format!("{:#?}\r\n", req.resource_map())
}

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    HttpServer::new(|| {
        App::new()
            .service(rmap)
            .service(
                web::scope("/x/")
                .service(web::resource("/path1").to(|| async { HttpResponse::Ok() }))
                .service(web::resource("/path2").route(web::get().to(|| HttpResponse::Ok())))
                .service(web::resource("/path3").route(web::head().to(|| HttpResponse::MethodNotAllowed())))
            )
        })
    .bind("127.0.0.1:8080")?
    .workers(1)
    .run()
    .await
}
```

**Comment by robjtede** [comment]
Nice! Can you paste here what it looks like for that config?

**Comment by mattgathu** [comment]
This is the output:
```
> http localhost:8080/rmap
HTTP/1.1 200 OK
content-length: 3907
content-type: text/plain; charset=utf-8
date: Fri, 25 Sep 2020 14:23:34 GMT

ResourceMap {
    root: ResourceDef {
        id: 0,
        tp: Static(
            "",
        ),
        name: "",
        pattern: "",
        elements: [
            Str(
                "",
            ),
        ],
    },
    parent: RefCell {
        value: (Weak),
    },
    named: {
        "rmap": ResourceDef {
            id: 0,
            tp: Static(
                "/rmap",
            ),
            name: "rmap",
            pattern: "/rmap",
            elements: [
                Str(
                    "/rmap",
                ),
            ],
        },
    },
    patterns: [
        (
            ResourceDef {
                id: 0,
                tp: Static(
                    "/rmap",
                ),
                name: "rmap",
                pattern: "/rmap",
                elements: [
                    Str(
                        "/rmap",
                    ),
                ],
            },
            None,
        ),
        (
            ResourceDef {
                id: 1,
                tp: Prefix(
                    "/x/",
                ),
                name: "",
                pattern: "/x/",
                elements: [
                    Str(
                        "/x/",
                    ),
                ],
            },
            Some(
                ResourceMap {
                    root: ResourceDef {
                        id: 0,
                        tp: Prefix(
                            "/x/",
                        ),
                        name: "",
                        pattern: "/x/",
                        elements: [
                            Str(
                                "/x/",
                            ),
                        ],
                    },
                    parent: RefCell {
                        value: (Weak),
                    },
                    named: {},
                    patterns: [
                        (
                            ResourceDef {
                                id: 0,
                                tp: Static(
                                    "/path1",
                                ),
                                name: "",
                                pattern: "/path1",
                                elements: [
                                    Str(
                                        "/path1",
                                    ),
                                ],
                            },
                            None,
                        ),
                        (
                            ResourceDef {
                                id: 1,
                                tp: Static(
                                    "/path2",
                                ),
                                name: "",
                                pattern: "/path2",
                                elements: [
                                    Str(
                                        "/path2",
                                    ),
                                ],
                            },
                            None,
                        ),
                        (
                            ResourceDef {
                                id: 2,
                                tp: Static(
                                    "/path3",
                                ),
                                name: "",
                                pattern: "/path3",
                                elements: [
                                    Str(
                                        "/path3",
                                    ),
                                ],
                            },
                            None,
                        ),
                    ],
                },
            ),
        ),
    ],
}
```

File: src/rmap.rs [hunk 1]
```diff
@@ -367,4 +367,32 @@ mod tests {
...
+        root.add(&mut ResourceDef::new("/v{version:[[:digit:]]{1}}"), None);
+        root.add(
+            &mut ResourceDef::root_prefix("/user/{id}"),
+            Some(Rc::new(user_map)),
+        );
+
+        let root = Rc::new(root);
+        root.finish(Rc::clone(&root));
+
+        println!("{:?}", root);
```
Comment (robjtede) [inline src/rmap.rs]: This would print a huge block in --nocapture scenarios (like our CI), can we use format! and make assertions about the last (and first) characters?

Comment (mattgathu) [reply src/rmap.rs]: good catch! 👍

Comment (robjtede) [reply src/rmap.rs]: almost, clippy wants a char pattern for the } 😅

**Review by robjtede — APPROVED** [review]
elegant solution to the problem 👍

**Comment by mattgathu** [comment]
@robjtede I don't know what to do about updating docs. The changes are internal to `ResourceMap` and not to consumer facing 🙂
