### PR TITLE
Fix Rustls 0.22 & 0.23 are limited to 256 handshakes per second.

### LINKED ISSUE #3407: TLS handshake rate limit adjustment does not work for rustls 0.22 & 0.23
Your issue may already be reported! Please search on the [Actix Web issue tracker](https://github.com/actix/actix-web/issues) before creating one.

## Expected Behavior

[HttpServer::method.max_connection_rate](https://docs.rs/actix-web/latest/actix_web/struct.HttpServer.html#method.max_connection_rate) should allow to adjust TLS handshakes per second as suggested by documentation when used with any version of rustls or openssl.

## Current Behavior

When used with `rustls 0.22` or `0.23` due to conditional compilation part of code to adjust handshake per seconds is ingored.

## Possible Solution

Will be provided as pull request.

## Steps to Reproduce (for bugs)

1. Receive `> 256` new TLS connections per second per worker.

## Context

In case of incoming TLS handshakes exceed default limit of `256` per second service to start accepting connection slower with part of the connections reset at TCP level.

## Your Environment

- Rust Version (I.e, output of `rustc -V`): `rustc 1.79.0 (129f3b996 2024-06-10)`
- Actix Web Version: `actix-web 4.7.0`

### PR DESCRIPTION
**Pull request by mstyura**
## PR Type

Bug Fix

## PR Checklist

- [x] ~Tests for the changes have been added / updated.~
- [x] ~Documentation comments have been added / updated.~
- [x] A changelog entry has been made for the appropriate packages.
- [x] Format code with the latest stable rustfmt.
- [x] (Team) Label with affected crates and semver status.

## Overview

Currently due to possibly accidentally missed features with `rustls 0.22` and `0.23` above configuration statement the server does not allow configuration of TLS handshakes limit per seconds.
The proposed approach is to define internal feature `__tls` and rely on it when writing feature conditions where it is expected to work on any tls implementation. Similar approach is already used by `__compress` feature. Such approach will make addition of new version of rustls less error prone.

The breaking change proposed is to make [HttpServer::method.max_connection_rate](https://docs.rs/actix-web/latest/actix_web/struct.HttpServer.html#method.max_connection_rate) conditionally defined based on `__tls` feature. This will make it obvious that this method take effect only for TLS connections rate.
This breaking change is completely avoidable just by moving feature condition inside method as it was before.

Closes #3407

### CODE REVIEW

File: actix-web/src/server.rs [hunk 1]
```diff
@@ -189,8 +183,8 @@ where
     ///
     /// By default max connections is set to a 256.
     #[allow(unused_variables)]
+    #[cfg(feature = "__tls")]
     pub fn max_connection_rate(self, num: usize) -> Self {
-        #[cfg(any(feature = "rustls-0_20", feature = "rustls-0_21", feature = "openssl"))]
```
Comment (robjtede) [inline actix-web/src/server.rs]: moving the flag like this is a breaking change, please move it back and we'll be able to get this merged

**Comment by mstyura** [comment]
Not sure if first two items in checklist are relevant. So will mark as ready for review and wait for a feedback.

File: actix-web/src/server.rs (hunk 1 above)
Comment (mstyura) [reply actix-web/src/server.rs]: Moved back to statement level, thanks for review!

**Review by robjtede — APPROVED** [review]
